# -*- coding: utf-8 -*-
"""Desafio HealthBit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_7k7Z6LYauKc8icjrO_hcvt-t1E3zpn

#Resolução teste técnico HealthBit

Este notebook possui as minhas resoluções das questões técnicas da etapa técnica para a vaga de estágio em Dados da empresa HealthBit.

##Informações iniciais

As células de códigos abaixo servem para subir as bases de dados e as bibliotecas pyhton que serão utilizados durante a resoluçõ dos exercícios.

OBS: As bases estão diferentes pois realizei alguns tratamentos simples nas planilhas excel para facilitar a manipulação
"""

pip install pandas

import pandas as pd
import matplotlib.pyplot as plt

# Carregando o arquivo Excel
sinistros_excel = '/Sinistros_base (2).xlsx'
cadastros_excel = '/Cadastro_base (2).xlsx'

# Carregar o arquivo Excel em um DataFrame
df_sinistros = pd.read_excel(sinistros_excel)
df_cadastros = pd.read_excel(sinistros_excel)

print(df_sinistros)
print("\n--------------------------------------------------------------\n")
print(df_cadastros)

"""## Resolução do exercício 1:

Questão: Sinistro do maior utilizador (High User), ou seja, qual beneficiário teve gastos mais elevados no período e qual foi o custo?
"""

# Agrupando as pessoas e realizando a soma dos custos delas
custo_por_pessoa = df_sinistros.groupby('CODIGO_PESSOA')['VL_EVENTO'].sum()

# Identificando qual pessoa tem o maior custo
id_pessoa_maior_gasto = custo_por_pessoa.idxmax()

# Identificando maior custo
custo_mais_elevados = custo_por_pessoa.max()

print('A pessoa que teve mais gastos tem o ID: ', id_pessoa_maior_gasto, ' e o custo foi de R$:', custo_mais_elevados)

"""## Resolução do exercício 2:

Questão: Apresente o custo de sinistro total (valor absoluto e %) e o custo de sinistro per capita (considerando número total de pessoas cadastradas) do período por plano.
"""

# Pegando o custo total por periodo e plano
custo_total = df_sinistros.groupby(['PERIODO', 'PLANO'])['VL_EVENTO'].sum().reset_index()

print("Custo total por periodo e plano:")
print(custo_total)

# Pegando a quantidade total de pessoas por periodo e plano
pessoas_total = df_sinistros.groupby(['PERIODO', 'PLANO'])['CODIGO_PESSOA'].nunique().reset_index()

# anexando dados de pessoas ao de valores
dados_sinistro_pessoas = pd.merge(custo_total, pessoas_total, on=['PERIODO', 'PLANO'], how='left')

# Pegando o custo de sinistro per capita
dados_sinistro_pessoas['CUSTO_PER_CAPITA'] = dados_sinistro_pessoas['VL_EVENTO'] / dados_sinistro_pessoas['CODIGO_PESSOA']

print("Custo per capita:")
print(dados_sinistro_pessoas)

# Calcular o custo de sinistro total em % (em relação ao total geral)
total_geral = dados_sinistro_pessoas['VL_EVENTO'].sum()
dados_sinistro_pessoas['Custo_PORCENTAGEM'] = (dados_sinistro_pessoas['VL_EVENTO'] / total_geral) * 100

print("Custo total em relação ao total geral em %")
print(dados_sinistro_pessoas)

"""## Resolução do exercício 3:

Questão: Qual o custo de sinistro (R$)  por mês/ano por data de referência?
"""

# Fazendo o casting de 'DT_EVENTO' para datetime
df_sinistros['DT_EVENTO'] = pd.to_datetime(df_sinistros['DT_EVENTO'])

# Pegando o mes da data de referencia
df_sinistros['MES_ANO'] = df_sinistros['DT_EVENTO'].dt.to_period('M')
df_sinistros['DT_REFERENCIA'] = df_sinistros['DT_EVENTO'].dt.date

# Calcular o custo de sinistro por mês/ano e data de referência
custo_por_mes_ano = df_sinistros.groupby(['MES_ANO', 'DT_REFERENCIA'])['VL_EVENTO'].sum().reset_index()

print("A tabela abaixo mostra os dados:")
print(custo_por_mes_ano)

"""## Resolução do exercício 4:

Questão: Qual plano traz mais preocupações em termos de custo? Por qual motivo?
"""

# Calcular o custo total de sinistro por plano
custo_plano = df_sinistros.groupby('PLANO')['VL_EVENTO'].sum()

print("Custo de sinistro por plano:")
print(custo_plano)
print()

# Grafico simples para ilustrar
custo_plano.plot(kind='bar')
plt.xlabel('Plano')
plt.ylabel('Custo total de sinistro')
plt.title('Custo total de sinistro por plano')
plt.show()

"""## Resolução do exercício 5:

Questão: Identificou algum problema na base que pode prejudicar a análise de dados? Qual(is) seriam?

Antes de iniciar a resolução das questões propostas, eu decide olhar um pouco das bases de dados e acabei realizando os seguintes tratamentos, no Excel, para melhorar a forma de lidar com os dados dentro do código:
* Em ambas as bases fiz a mudança dos nomes dos atributos/colunas visando remover os acentos/espaços entre os nomes e encurtá-los.
* Fiz o processo de remoção dos dados duplicados em ambas as bases.
* Mudei os valores da coluna de INTERNAÇÃO da base de sinistros para 0 e 1 (valores booleanos) no lugar de sim ou não.

Procedimentos de tratamento/normalização dos dados são importantes, pois evitam que as análises feitas em cima da base sejam inconsistentes.
Um exemplo de erro que poderia acontecer nestas bases seria o cálculo errado dos valores de custo que precisaram ser feitos em quase todos os exercícios. Se esses cálculos forem feitos com dados suplicados, os valores serão maiores do que deveriam ser, e a análise estaria errada.



"""